# Generated by Django 4.2 on 2024-12-04 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_alter_transaction_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
